name: Deploy ReTaskMe to Azure

on:
  push:
    branches:
      - devel

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET Core 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Azure Login with Service Principal
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}", "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}", "tenantId":"${{ secrets.AZURE_TENANT_ID }}", "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'

    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_SERVER_URL }} \
          --username ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      run: |
        IMAGE=${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/retaskme-app:latest
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Update App Service to use Docker image
      run: |
        az webapp config container set \
          --name retaskme \
          --resource-group retaskme \
          --docker-custom-image-name ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}/retaskme-app:latest \
          --docker-registry-server-url ${{ secrets.DOCKER_REGISTRY_SERVER_URL }} \
          --docker-registry-server-user ${{ secrets.DOCKER_REGISTRY_SERVER_USERNAME }} \
          --docker-registry-server-password ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}
