name: Deploy ReTaskMe to Azure

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET Core 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Publish Application
      run: dotnet publish ReTaskMe.sln -c Release -o ./publish-output

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'retaskme' 
        slot-name: 'production' 
        package: './publish-output'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
